In [2]:
import pandas as pd
import numpy as np

In [4]:
veriler=np.random.randint(1,50,[4,5])
#numpy sınıfından 1'den 50'ye kadar 4 satır 5 sütunluk rastgele sayılardan oluşan bir dizi oluşturduk

In [5]:
veriler

array([[17, 39, 12,  9,  6],
       [ 1,  6,  9,  7, 41],
       [45, 36,  7, 37, 16],
       [26, 47, 45, 44, 48]])

In [6]:
df=pd.DataFrame(veriler)#veriler dizinden oluşan df adında bir dataframe oluşturduk

In [7]:
df

    0   1   2   3   4
0  17  39  12   9   6
1   1   6   9   7  41
2  45  36   7  37  16
3  26  47  45  44  48

In [17]:
df=pd.DataFrame(veriler,columns=["s1","s2","s3","s4","s5"],index=["st1","st2","st3","st4"])
df

     s1  s2  s3  s4  s5
st1  17  39  12   9   6
st2   1   6   9   7  41
st3  45  36   7  37  16
st4  26  47  45  44  48

In [18]:
veriler=[["Musti","Yıldız",19],["Asmin","Sayim",17]]

In [20]:
df=pd.DataFrame(veriler,columns=["İsim","Soyisim","Yaş"],index=["Ogr1","Ogr2"])
df

       İsim Soyisim  Yaş
Ogr1  Musti  Yıldız   19
Ogr2  Asmin   Sayim   17

In [21]:
df=pd.read_csv("diabetes_data_upload.csv")
#diabet veri setini df isimli dataframe atadık

In [22]:
df

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,39,Female,Yes,Yes,Yes,No,Yes,No,No,Yes,No,Yes,Yes,No,No,No,Positive
516,48,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,No,Positive
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive
518,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [23]:
df.head(2)#ilk iki satırı gösterir

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive

In [24]:
df.tail(3)#son üç satırı gösterir

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive
518,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [25]:
df.shape #satır ve sütun sayısını verir

(520, 17)

In [26]:
df.info # veri setiyle ilgili genel bilgileri verir

<bound method DataFrame.info of      Age  Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0     40    Male       No        Yes                 No      Yes         No
1     58    Male       No         No                 No      Yes         No
2     41    Male      Yes         No                 No      Yes        Yes
3     45    Male       No         No                Yes      Yes        Yes
4     60    Male      Yes        Yes                Yes      Yes        Yes
..   ...     ...      ...        ...                ...      ...        ...
515   39  Female      Yes        Yes                Yes       No        Yes
516   48  Female      Yes        Yes                Yes      Yes        Yes
517   58  Female      Yes        Yes                Yes      Yes        Yes
518   32  Female       No         No                 No      Yes         No
519   42    Male       No         No                 No       No         No

    Genital thrush visual blurring Itching Irritability delayed healing  \
0               No              No     Yes           No             Yes
1               No             Yes      No           No              No
2               No              No     Yes           No             Yes
3              Yes              No     Yes           No             Yes
4               No             Yes     Yes          Yes             Yes
..             ...             ...     ...          ...             ...
515             No              No     Yes           No             Yes
516             No              No     Yes          Yes             Yes
517             No             Yes      No           No              No
518             No             Yes     Yes           No             Yes
519             No              No      No           No              No

    partial paresis muscle stiffness Alopecia Obesity     class
0                No              Yes      Yes     Yes  Positive
1               Yes               No      Yes      No  Positive
2                No              Yes      Yes      No  Positive
3                No               No       No      No  Positive
4               Yes              Yes      Yes     Yes  Positive
..              ...              ...      ...     ...       ...
515             Yes               No       No      No  Positive
516             Yes               No       No      No  Positive
517             Yes              Yes       No     Yes  Positive
518              No               No      Yes      No  Negative
519              No               No       No      No  Negative

[520 rows x 17 columns]>

In [27]:
df.ndim # veri setinin boyutunu verir

2

In [28]:
df.size # veri setinde kaç adet veri olduğunu gösterir

8840